### PR TITLE
Create .gitattributes

### PR DESCRIPTION
**Pull request by Luigifan**
ignores all the code in the specified folders as it adds misleading code to the github counter thingy :P
it doesn't affect the local repository any. all it is is for github's statistics.

### CODE REVIEW

**Comment by Wohlstand** [comment]
Oh,  neat, thanks,  but in the _common folder is a shared PGE code, but add the "Contents" and "Documents" folders where is no code, help documents, specificatiins, readmes and configs only

**Comment by Luigifan** [comment]
Will do! Is it possible to build PGE on Mac OS X 10.7.5? If so, I may make some Mac specific tweaks to make the editors fit in more under OS X

**Comment by Wohlstand** [comment]
No, needed Mac OS X 10.9 because Qt itself requires newer clang and xcode features which are available in Mac OS X 10.9 and higher only

**Comment by Luigifan** [comment]
I have Qt 5.5.1 on OS X 10.7. But I forgot you statically link everything. Ah, oh well.
screen shot 2016-03-17 at 8 40 27 am

**Comment by Luigifan** [comment]
I could still link Qt dynamically just to test though, correct?

**Comment by Wohlstand** [comment]
Yes, you can. Anyway for debug I always using dynamic build, but for release I building static version

**Comment by Luigifan** [comment]
I will try later. Have you looked into the bug where clicking and dragging moves the whole window?

**Comment by Wohlstand** [comment]
Not yet, but anyway with new hardware my old VM which runs OS X works perfectly and I can debug software on it.

**Comment by Luigifan** [comment]
```
In file included from dynamic_modplug.c:24:
In file included from ../_builds/macos/frameworks/SDL2.framework/Headers/SDL2/SDL_loadso.h:44:
In file included from ../_builds/macos/frameworks/SDL2.framework/Headers/SDL2/SDL_stdinc.h:31:
In file included from ../_builds/macos/frameworks/SDL2.framework/Headers/SDL2/SDL_config.h:25:
../_builds/macos/frameworks/SDL2.framework/Headers/SDL2/SDL_platform.h:71:10: fatal error:
      'AvailabilityMacros.h' file not found
#include "AvailabilityMacros.h"
```
yup, looks like i can't build on 10.7.5 (while running build_deps.sh)
